### ISSUE TITLE
findOneValidPassphrase crashes when given an incorrectly hashed passphrase

### ISSUE THREAD

**Issue by mickael-menu** [readium/r2-lcp-swift#76]
Calling `findOneValidPassphrase` crashes when provided a hashed passphrase that can't be parsed.

`Botan::Invalid_Argument: Invalid argument hex_decode: invalid hex character 'z'.`

It should return `nil` instead.

**Comment by danielweck** [comment]
I remember experiencing this issue in Thorium (`readium-desktop`) with prototype authenticated-OPDS feeds that contained the LCP passphrase in incorrect format (base64 vs. hex of SHA256). At the application level, I implemented a check in order to handle both the valid and the invalid case (for legacy reasons, just so we can continue to test with OPDS feeds that are otherwise correct).

At the lib-wrapper level (i.e. `r2-lcp-js`) if I remember correctly a native C++ exception is not automatically handled by JavaScript try/catch blocks, so the crash is fatal indeed. Is it the same with iOS-Swift and Android-Kotlin?

**Comment by mickael-menu** [comment]
> At the lib-wrapper level (i.e. `r2-lcp-js`) if I remember correctly a native C++ exception is not automatically handled by JavaScript try/catch blocks, so the crash is fatal indeed. Is it the same with iOS-Swift and Android-Kotlin?

We might be able to catch it at the private framework level (Objective-C++), but not at the Swift level (`r2-lcp-swift`). For Android I'm not sure.

I just implemented a check using a regex to determine if the provided passphrase is a proper SHA-256 hash: https://github.com/readium/r2-lcp-swift/commit/f6d3f5f5527bce9fd33df581100376037d797c3d
That might be a sufficient workaround for now, but we might want to catch this exception next time we need to update the lib.
